name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request] "
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      Thank you for contributing to EhPanda! 
      
      Before you submit your feature request, please complete each text area below with the relevant details for your request, and complete the steps in the checklist
- type: textarea
  attributes:
    label: Description
    description: |
      Provide a clear and concise description of the feature you'd like, or any alternative features you've considered. 
  validations:
    required: true
- type: textarea
  attributes:
    label: Context
    description: |
      Provide any other context or screenshots about the feature request. 
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Checklist
    options:
    - label: I’m interested in submitting a pull request to implement this feature.
      required: false
    - label: This feature hasn't been addressed in an [existing GitHub issue](https://github.com/EhPanda-Team/EhPanda/issues) or [discussion](https://github.com/EhPanda-Team/EhPanda/discussions).
      required: true
